from pathlib import Path
p = Path('app.js')
s = p.read_text(encoding='utf-8')
s = s.replace('join(" â€¢ ")', 'join(" | ")')
s = s.replace('Day 1 Arrival â€¢ Day 2 North Goa â€¢ Day 3 South Goa â€¢ Day 4 Leisure â€¢ Day 5 Return', 'Day 1 Arrival | Day 2 North Goa | Day 3 South Goa | Day 4 Leisure | Day 5 Return')
s = s.replace('Day 1 Volvo â€¢ Day 2 Manali local â€¢ Day 3 Solang â€¢ Day 4 Atal Tunnel â€¢ Day 5 Leisure â€¢ Day 6 Return', 'Day 1 Volvo | Day 2 Manali local | Day 3 Solang | Day 4 Atal Tunnel | Day 5 Leisure | Day 6 Return')
s = s.replace('Srinagar â€¢ Gulmarg â€¢ Pahalgam â€¢ Sonmarg â€¢ Houseboat â€¢ Return', 'Srinagar | Gulmarg | Pahalgam | Sonmarg | Houseboat | Return')
s = s.replace('Cochin â€¢ Munnar â€¢ Thekkady â€¢ Alleppey â€¢ Cochin', 'Cochin | Munnar | Thekkady | Alleppey | Cochin')
s = s.replace('Jaipur â€¢ Jodhpur â€¢ Udaipur â€¢ Pushkar â€¢ Return', 'Jaipur | Jodhpur | Udaipur | Pushkar | Return')
s = s.replace('Ayodhya â€¢ Varanasi â€¢ Sarnath â€¢ Return', 'Ayodhya | Varanasi | Sarnath | Return')
helpers = '''\nconst iconSvg = {\n  plane: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M21 16v-2L8 5V3.5C8 2.7 7.3 2 6.5 2S5 2.7 5 3.5V5L2 7v2l3-.9V14l-2 1.5V17l3.5-1 3.5 1v-1.5L8 14V8.1L21 16Z"/></svg>',\n  home: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 11 12 4l9 7v9a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1v-9Z"/></svg>',\n  sun: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 7a5 5 0 1 0 0 10 5 5 0 0 0 0-10Zm0-5v3M12 19v3M4.2 4.2l2.1 2.1M17.7 17.7l2.1 2.1M2 12h3M19 12h3M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1"/></svg>',\n  grid: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h7v7H4V4Zm9 0h7v7h-7V4ZM4 13h7v7H4v-7Zm9 0h7v7h-7v-7Z"/></svg>',\n  star: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 2 2.9 6 6.6.9-4.8 4.7 1.1 6.6L12 17.1l-5.8 3.1 1.1-6.6-4.8-4.7 6.6-.9L12 2Z"/></svg>'\n};\nconst serviceIcons = [iconSvg.plane, iconSvg.home, iconSvg.sun, iconSvg.grid];\nconst starIcons = () => `<span class="star-icons" aria-label="5 star rating">${iconSvg.star.repeat(5)}</span>`;\n'''
if 'const iconSvg =' not in s:
    s = s.replace('const whatsappText = "Hello RR Tourism, I want more information about your tour packages.";\n', 'const whatsappText = "Hello RR Tourism, I want more information about your tour packages.";\n' + helpers, 1)
intl = '''\n\nconst internationalHolyPlaces = [\n  { name: "Makkah Umrah Package", faith: "Muslim", duration: "7N/8D", price: 69999, highlights: "Umrah guidance | Makkah stay | Madinah optional", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kaaba%20Masjid%20Haram%20Makkah.jpg" },\n  { name: "Vatican City Pilgrimage", faith: "Christian", duration: "5N/6D", price: 129999, highlights: "St. Peter's Basilica | Vatican Museums | Rome churches", image: "https://commons.wikimedia.org/wiki/Special:FilePath/St%20Peter%27s%20Basilica%20facade%2C%20Rome%2C%20Italy.jpg" },\n  { name: "Jerusalem Holy Land Tour", faith: "Multi-faith", duration: "6N/7D", price: 149999, highlights: "Old City | Western Wall | Church visits | Dome views", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Jerusalem-2013-Temple%20Mount-Dome%20of%20the%20Rock-Detail%2001.jpg" },\n  { name: "Lumbini Buddhist Circuit", faith: "Buddhist", duration: "4N/5D", price: 52999, highlights: "Maya Devi Temple | Monasteries | Nepal assistance", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Lumbini%2C%20Maya%20Devi%20Temple.jpg" },\n  { name: "Kartarpur Sahib Darshan", faith: "Sikh", duration: "3N/4D", price: 39999, highlights: "Kartarpur Sahib | Amritsar connection | Document guidance", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Gurdwara%20Darbar%20Sahib%20Kartarpur.jpg" },\n  { name: "Pashupatinath Nepal Yatra", faith: "Hindu", duration: "4N/5D", price: 45999, highlights: "Pashupatinath Temple | Kathmandu sightseeing | Local transfers", image: "https://commons.wikimedia.org/wiki/Special:FilePath/Pashupatinath%20Temple%20Kathmandu.jpg" }\n];\n'''
if 'const internationalHolyPlaces =' not in s:
    s = s.replace('const packages = [', intl + '\nconst packages = [', 1)
s = s.replace('<div class="service-icon">${["âœˆ", "âŒ‚", "â˜¼", "â–£"][index % 4]}</div>', '<div class="service-icon">${serviceIcons[index % serviceIcons.length]}</div>')
s = s.replace('<div class="rating">â˜…â˜…â˜…â˜…â˜… ${dest.rating}</div>', '<div class="rating">${starIcons()} ${dest.rating}</div>')
s = s.replace('<div class="stars">â˜…â˜…â˜…â˜…â˜…</div>', '<div class="stars">${starIcons()}</div>')
s = s.replace('${cat}${cat.includes("Videos") ? " â–¶" : ""}', '${cat}${cat.includes("Videos") ? " Play" : ""}')
render = '''\n\nfunction renderInternationalHolyPlaces(filter = "All") {\n  const filters = ["All", ...new Set(internationalHolyPlaces.map(place => place.faith))];\n  document.getElementById("internationalHolyFilters").innerHTML = filters.map((faith, index) => `<button class="${(filter === faith || (filter === "All" && index === 0)) ? "active" : ""}" data-international-holy="${faith}">${faith === "All" ? "All International Holy Trips" : faith + " Trips"}</button>`).join("");\n  const list = filter === "All" ? internationalHolyPlaces : internationalHolyPlaces.filter(place => place.faith === filter);\n  document.getElementById("internationalHolyGrid").innerHTML = list.map(place => `\n    <article class="destination-card reveal">\n      <div class="badge-row"><span class="badge">International</span><span class="badge">${place.faith}</span></div>\n      <img src="${place.image}" alt="${place.name} international holy trip by RR Tourism" loading="lazy" />\n      <div class="card-body">\n        <h3>${place.name}</h3>\n        <div class="meta"><span>${place.duration}</span><span>${place.faith}</span></div>\n        <p>${place.highlights}</p>\n        <div class="price">From ${rupee(place.price)}</div>\n        <div class="card-actions">\n          <a class="btn primary" href="#contact" data-enquiry="${place.name}">Send Enquiry</a>\n          <a class="btn whatsapp" target="_blank" rel="noopener noreferrer" href="${whatsappUrl(`Hello RR Tourism, I want information about ${place.name}.`)}">WhatsApp</a>\n        </div>\n      </div>\n    </article>`).join("");\n  observeReveals();\n}\n'''
if 'function renderInternationalHolyPlaces' not in s:
    s = s.replace('function renderGallery(filter = "All") {', render + '\nfunction renderGallery(filter = "All") {', 1)
if 'internationalHolyFilters' not in s[s.find('setupInteractions'):s.find('document.getElementById("galleryGrid")')]:
    s = s.replace('  document.getElementById("holyFilters")?.addEventListener("click", e => {\n    if (e.target.matches("button")) renderHolyPlaces(e.target.dataset.holy);\n  });', '  document.getElementById("holyFilters")?.addEventListener("click", e => {\n    if (e.target.matches("button")) renderHolyPlaces(e.target.dataset.holy);\n  });\n  document.getElementById("internationalHolyFilters")?.addEventListener("click", e => {\n    if (e.target.matches("button")) renderInternationalHolyPlaces(e.target.dataset.internationalHoly);\n  });')
s = s.replace('  renderHolyPlaces();', '  renderHolyPlaces();\n  renderInternationalHolyPlaces();')
p.write_text(s, encoding='utf-8')
